# Generated by Django 5.2 on 2025-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('electronics', 'Electronics'), ('home', 'Home'), ('beauty', 'Beauty'), ('sports', 'Sports')], max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('tshirt', 'T-Shirts'), ('shirt', 'Shirts'), ('denim', 'Denims'), ('pants', 'Pants & Trousers')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
